[package]
authors = ["Manuel Mauro <manuel.mauro@protonmail.com>"]
edition = "2018"
name = "algorust"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.3.1"
indexmap = "1.6.1"
lazy_static = "1.4.0"
rand = "0.8.1"
reqwest = "0.9.20"
ring = "0.16.19"
rmp = "0.8.8"
rmp-serde = "0.14.0"
serde = {version = "1.0", features = ["derive"]}
serde_bytes = "0.11"
serde_json = "1.0.40"
sha2 = "0.8.0"
static_assertions = "0.3.4"

[dev-dependencies]
chrono = "0.4.9"
dirs = "2.0"
