[package]
authors = ["Manuel Mauro <manuel.mauro@protonmail.com>"]
description = "A Rusty sdk for the Algorand blockchain."
edition = "2018"
keywords = ["Algorand", "sdk"]
license = "MIT"
name = "algorand-rs"
repository = "https://github.com/manuelmauro/algorand-rs"
version = "0.1.1"

[dependencies]
data-encoding = "2.3.1"
derive_more = "0.99.11"
indexmap = "1.6.1"
lazy_static = "1.4.0"
rand = "0.8.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }
ring = "0.16.19"
rmp = "0.8.8"
rmp-serde = "0.14.0"
serde = {version = "1.0", features = ["derive"]}
serde_bytes = "0.11"
serde_json = "1.0.40"
sha2 = "0.8.0"
static_assertions = "0.3.4"
thiserror = "1.0.23"
url = "2.2.0"

[dev-dependencies]
chrono = "0.4.9"
dirs = "2.0"
dotenv = "0.15.0"
